name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            zlib1g-dev \
            liblzma-dev \
            libbz2-dev \
            libssl-dev \
            libreadline-dev \
            libsqlite3-dev \
            libffi-dev \
            python3-pip \
            xz-utils \
            zip

      - name: Install pyenv
        run: |
          curl https://pyenv.run | bash
          echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $HOME/.bashrc
          echo 'eval "$(pyenv init --path)"' >> $HOME/.bashrc
          echo 'eval "$(pyenv virtualenv-init -)"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Install Python 3.13 via pyenv
        run: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv virtualenv-init -)"
          pyenv install 3.13-dev
          pyenv global 3.13-dev

      - name: Verify Python Modules
        run: |
          python -c "import bz2, gzip, lzma, zlib; print('Compression modules available!')"

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Bot
        env:
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python bot.py
